/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Atoms/Button.vue')['default']
    DetailsInfo: typeof import('./src/components/Molecules/DetailsInfo.vue')['default']
    EventDetails: typeof import('./src/components/Templates/EventDetails.vue')['default']
    Hero: typeof import('./src/components/Templates/Hero.vue')['default']
    Modal: typeof import('./src/components/Atoms/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeFoot: typeof import('./src/components/Molecules/WelcomeFoot.vue')['default']
    WelcomeMsg: typeof import('./src/components/Molecules/WelcomeMsg.vue')['default']
  }
}
