/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/Atoms/BottomSheet.vue')['default']
    Button: typeof import('./src/components/Atoms/Button.vue')['default']
    CacheStatus: typeof import('./src/components/Dev/CacheStatus.vue')['default']
    Card: typeof import('./src/components/Atoms/Card.vue')['default']
    CheckBox: typeof import('./src/components/Atoms/CheckBox.vue')['default']
    CookieBanner: typeof import('./src/components/Molecules/CookieBanner.vue')['default']
    DecorativeBranches: typeof import('./src/components/Atoms/DecorativeBranches.vue')['default']
    DeleteGoodWillModal: typeof import('./src/components/Templates/DeleteGoodWillModal.vue')['default']
    DetailsInfo: typeof import('./src/components/Molecules/DetailsInfo.vue')['default']
    EventDetails: typeof import('./src/components/Templates/EventDetails.vue')['default']
    Gallery: typeof import('./src/components/Templates/Gallery.vue')['default']
    GalleryView: typeof import('./src/views/GalleryView.vue')['default']
    GiftBottomSheet: typeof import('./src/components/Templates/GiftBottomSheet.vue')['default']
    GiftItemCard: typeof import('./src/components/Molecules/GiftItemCard.vue')['default']
    GiftItemsList: typeof import('./src/components/Organisms/GiftItemsList.vue')['default']
    HeaderNavigation: typeof import('./src/components/Organisms/HeaderNavigation.vue')['default']
    Hero: typeof import('./src/components/Templates/Hero.vue')['default']
    Input: typeof import('./src/components/Atoms/Input.vue')['default']
    Loader: typeof import('./src/components/Atoms/loader.vue')['default']
    LoaderItemsList: typeof import('./src/components/Atoms/LoaderItemsList.vue')['default']
    LoveStory: typeof import('./src/components/Templates/LoveStory.vue')['default']
    MainWebsiteView: typeof import('./src/views/MainWebsiteView.vue')['default']
    ManageGoodWillMessageModal: typeof import('./src/components/Templates/ManageGoodWillMessageModal.vue')['default']
    ManagePlusOneModal: typeof import('./src/components/Templates/ManagePlusOneModal.vue')['default']
    MediaLightbox: typeof import('./src/components/Molecules/MediaLightbox.vue')['default']
    Modal: typeof import('./src/components/Atoms/Modal.vue')['default']
    PaymentValidation: typeof import('./src/views/PaymentValidation.vue')['default']
    PrivacyPolicy: typeof import('./src/views/PrivacyPolicy.vue')['default']
    RemovePlusOneModal: typeof import('./src/components/Templates/RemovePlusOneModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RSVP: typeof import('./src/components/Templates/RSVP.vue')['default']
    Tabs: typeof import('./src/components/Atoms/Tabs.vue')['default']
    ToggleButton: typeof import('./src/components/Atoms/ToggleButton.vue')['default']
    ToggleSwitch: typeof import('./src/components/Atoms/ToggleSwitch.vue')['default']
    UpdateRsvpModal: typeof import('./src/components/Templates/UpdateRsvpModal.vue')['default']
    WeddingLogo: typeof import('./src/components/Atoms/WeddingLogo.vue')['default']
    WelcomeModal: typeof import('./src/components/Templates/WelcomeModal.vue')['default']
  }
}
