/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/Atoms/BottomSheet.vue')['default']
    Button: typeof import('./src/components/Atoms/Button.vue')['default']
    CacheStatus: typeof import('./src/components/Dev/CacheStatus.vue')['default']
    Card: typeof import('./src/components/Atoms/Card.vue')['default']
    CookieBanner: typeof import('./src/components/Molecules/CookieBanner.vue')['default']
    DeleteGoodWillDialog: typeof import('./src/components/Molecules/DeleteGoodWillDialog.vue')['default']
    DeleteGoodWillFooter: typeof import('./src/components/Molecules/DeleteGoodWillFooter.vue')['default']
    DeleteGoodWillModal: typeof import('./src/components/Templates/DeleteGoodWillModal.vue')['default']
    DetailsInfo: typeof import('./src/components/Molecules/DetailsInfo.vue')['default']
    EventDetails: typeof import('./src/components/Templates/EventDetails.vue')['default']
    Gallery: typeof import('./src/components/Templates/Gallery.vue')['default']
    GiftBottomSheet: typeof import('./src/components/Templates/GiftBottomSheet.vue')['default']
    GiftFailedModal: typeof import('./src/components/Molecules/GiftFailedModal.vue')['default']
    GiftingFooter: typeof import('./src/components/Molecules/GiftingFooter.vue')['default']
    GiftingForm: typeof import('./src/components/Molecules/GiftingForm.vue')['default']
    GiftSuccessModal: typeof import('./src/components/Molecules/GiftSuccessModal.vue')['default']
    GiftSummary: typeof import('./src/components/Molecules/GiftSummary.vue')['default']
    GiftSummaryFooter: typeof import('./src/components/Molecules/GiftSummaryFooter.vue')['default']
    GoodWillFooter: typeof import('./src/components/Molecules/GoodWillFooter.vue')['default']
    GoodWillForm: typeof import('./src/components/Molecules/GoodWillForm.vue')['default']
    GuestIdentifierView: typeof import('./src/views/GuestIdentifierView.vue')['default']
    Hero: typeof import('./src/components/Templates/Hero.vue')['default']
    Input: typeof import('./src/components/Atoms/Input.vue')['default']
    Loader: typeof import('./src/components/Atoms/loader.vue')['default']
    LoveStory: typeof import('./src/components/Templates/LoveStory.vue')['default']
    MainWebsiteView: typeof import('./src/views/MainWebsiteView.vue')['default']
    ManageGoodWillMessageModal: typeof import('./src/components/Templates/ManageGoodWillMessageModal.vue')['default']
    ManagePlusOneModal: typeof import('./src/components/Templates/ManagePlusOneModal.vue')['default']
    MediaLightbox: typeof import('./src/components/Molecules/MediaLightbox.vue')['default']
    Modal: typeof import('./src/components/Atoms/Modal.vue')['default']
    PlusOneFooter: typeof import('./src/components/Molecules/PlusOneFooter.vue')['default']
    PlusOneForm: typeof import('./src/components/Molecules/PlusOneForm.vue')['default']
    PrivacyPolicy: typeof import('./src/views/PrivacyPolicy.vue')['default']
    RemovePlusOneDialog: typeof import('./src/components/Molecules/RemovePlusOneDialog.vue')['default']
    RemovePlusOneFooter: typeof import('./src/components/Molecules/RemovePlusOneFooter.vue')['default']
    RemovePlusOneModal: typeof import('./src/components/Templates/RemovePlusOneModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RSVP: typeof import('./src/components/Templates/RSVP.vue')['default']
    ToggleButton: typeof import('./src/components/Atoms/ToggleButton.vue')['default']
    ToggleSwitch: typeof import('./src/components/Atoms/ToggleSwitch.vue')['default']
    UpdateRSVPDialog: typeof import('./src/components/Molecules/UpdateRSVPDialog.vue')['default']
    UpdateRSVPFooter: typeof import('./src/components/Molecules/UpdateRSVPFooter.vue')['default']
    UpdateRsvpModal: typeof import('./src/components/Templates/UpdateRsvpModal.vue')['default']
    WelcomeFoot: typeof import('./src/components/Molecules/WelcomeFoot.vue')['default']
    WelcomeModal: typeof import('./src/components/Templates/WelcomeModal.vue')['default']
    WelcomeMsg: typeof import('./src/components/Molecules/WelcomeMsg.vue')['default']
  }
}
